package world.spacenet.corona_bi.extract_data.domain;

public class Properties {
    public String Gender;
    public String Hospital_Pref;
    public String PCR検査実施人数;
    public String PCR検査前日比;
    public String Release;
    public String Residential;
    public Float X;
    public Float Y;
    public String キー;
    public String ステータス;
    public String ソース;
    public String ソース2;
    public String ソース3;
    public String チャーター便;
    public Double 確定日;
    public Double 確定日YYYYMMDD;
    public String 居住管内;
    public String 居住市区町村;
    public String 居住都道府県;
    public String 勤務先_正誤確認用;
    public String 厚生省NO;
    public Double 更新日時;
    public String 国内;
    public String 市区町村内症例番号;
    public String 死者合計;
    public String 受診都道府県;
    public String 受診都道府県コード;
    public String 職業_正誤確認用;
    public Integer 人数;
    public String 性別;
    public Integer 前日比;
    public Integer 退院数;
    public Integer 退院数累計;
    public Integer 通し;
    public String 都道府県内症例番号;
    public String 年代;
    public Integer 発症数;
    public String 発症日;
    public String 発表;
    public String 備考;
    public String 無症状病原体保有者;
    public Integer 累計;
    public Integer ObjectId;
}
